package com.unityagent.agent.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.Collections;
import java.util.Map;
import java.util.Objects;

/**
 * Provider-neutral representation of a tool call generated by an LLM.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ToolCall {

    private final String id;
    private final String name;
    private final Map<String, Object> arguments;
    private final String rawArguments;

    public ToolCall(String id, String name, Map<String, Object> arguments, String rawArguments) {
        this.id = Objects.requireNonNull(id, "ToolCall id cannot be null");
        this.name = Objects.requireNonNull(name, "ToolCall name cannot be null");
        this.arguments = arguments != null ? Collections.unmodifiableMap(arguments) : Map.of();
        this.rawArguments = rawArguments != null ? rawArguments : "{}";
    }

    public static ToolCall of(String id, String name, Map<String, Object> arguments) {
        return new ToolCall(id, name, arguments, null);
    }

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public Map<String, Object> getArguments() {
        return arguments;
    }

    public String getRawArguments() {
        return rawArguments;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ToolCall toolCall = (ToolCall) o;
        return Objects.equals(id, toolCall.id) && Objects.equals(name, toolCall.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name);
    }

    @Override
    public String toString() {
        return "ToolCall{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", arguments=" + arguments +
                '}';
    }
}
